In [2]:
import torch
torch.__version__

'2.10.0+cu126'

Tensors

In [4]:
#salar - tensor with dim(zero)
tensor0 = torch.tensor(1)
tensor0.ndim

0

In [6]:
#vector - tensor with dim(1)
tensor1 = torch.tensor([1,2,3,4,5])
print(f"Vector: {tensor1} , Dim: {tensor1.ndim}, Shape: {tensor1.shape}")
#matrix - tensor with dim(2)
tensor2 = torch.tensor([[1,0,0],[0,1,0]])
print(f"Matrix: {tensor2} , Dim: {tensor2.dim()}, Shape: {tensor2.size()}")
#ndim = dim and shape = size

Vector: tensor([1, 2, 3, 4, 5]) , Dim: 1, Shape: torch.Size([5])
Matrix: tensor([[1, 0, 0],
        [0, 1, 0]]) , Dim: 2, Shape: torch.Size([2, 3])


In [ ]:
#Ways to create tensors
#using Size
size = (3,4)
tensor4 = torch.empty(size)
#Creating Random Tensor (values auto asigned btwn. 0 and 1)
tensor5 = torch.rand(size)
tensor5.dtype
# .dtype returns the tensor type (int,float et. al.) Default type: float32
# type can be be assigned during the creation or can be modified later using type(torch.newType)


torch.float32

In [ ]:
#Creating Tensors using Numpy Array
import numpy as np

exampleArray = np.array([[1,2],[3,4]])
tensor6 = torch.tensor(exampleArray) #Passed by Value
tensor7 = torch.from_numpy(exampleArray) #Share Same memory - Passed by Reference

exampleArray *= 5
print(exampleArray)
print(tensor6) # No UPDATION
print(tensor7) 

[[ 5 10]
 [15 20]]
tensor([[1, 2],
        [3, 4]])
tensor([[ 5, 10],
        [15, 20]])


Device is the attribute of the tensor that tells the location of the tensor (loc on GPU or CPU)

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor8 = torch.ones(3,7).to(device) #"CPU" -> "cuda"
tensor9 = torch.zeros(3,7, device = device) # -> 'cuda' 

Assessing Elements in Tensor

In [12]:
print(tensor7[0])
print(tensor7[1,0])

#Slicing
print(tensor7[:, 1]) #Column
print(tensor7[0,:]) #Row

tensor([ 5, 10])
tensor(15)
tensor([10, 20])
tensor([ 5, 10])


Operation of Tensor

In [13]:
tensor10 = torch.rand(2,3)
tensor11 = torch.ones(2,3)
print(tensor10)
print(tensor11)

tensor([[0.7689, 0.4249, 0.6431],
        [0.2357, 0.5128, 0.8063]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
# elementwise addition
tensor12 = tensor10 + tensor11
# torch.add(tensor10,tensor11)
print(tensor12)

# elementwise subtraction
tensor13 = tensor10 - tensor11
# torch.sub(tensor10,tensor11)
print(tensor13)

# elementwise multiplication
tensor14 = tensor10 * tensor11
# torch.mul(tensor10,tensor11)
print(tensor14)

# elementwise division
tensor15 = tensor10 / tensor11
# torch.div(tensor10,tensor11)
print(tensor15)

tensor([[1.7689, 1.4249, 1.6431],
        [1.2357, 1.5128, 1.8063]])
tensor([[-0.2311, -0.5751, -0.3569],
        [-0.7643, -0.4872, -0.1937]])
tensor([[0.7689, 0.4249, 0.6431],
        [0.2357, 0.5128, 0.8063]])
tensor([[0.7689, 0.4249, 0.6431],
        [0.2357, 0.5128, 0.8063]])


Tensor Manupulation 

In [ ]:
x = torch.randint(0,3,(3,3)) #(range(size))
x

tensor([[2, 1, 1],
        [1, 1, 1],
        [1, 2, 2]])

In [30]:
y = x.view(9)
z = x.view(-1,9)
print(x.shape,y.shape,z.shape)
print(x)
print(y)
print(z)

torch.Size([3, 3]) torch.Size([9]) torch.Size([1, 9])
tensor([[2, 1, 1],
        [1, 1, 1],
        [1, 2, 2]])
tensor([2, 1, 1, 1, 1, 1, 1, 2, 2])
tensor([[2, 1, 1, 1, 1, 1, 1, 2, 2]])


In [34]:
d = torch.cat((tensor15,tensor14),dim=0)
d

tensor([[0.7689, 0.4249, 0.6431],
        [0.2357, 0.5128, 0.8063],
        [0.7689, 0.4249, 0.6431],
        [0.2357, 0.5128, 0.8063]])